export const GET_USERS = 'GET_USERS'

export const GET_ALL_MEETINGS = 'GET_ALL_MEETINGS'
export const GET_FILTERED_MEETINGS = 'GET_FILTERED_MEETINGS'
export const CHOOSE_MEETING_FOR_DELETING = 'CHOOSE_MEETING_FOR_DELETING'

export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const SHOW_CONFIRM_LOGOUT_MODAL = 'SHOW_CONFIRM_LOGOUT_MODAL'
export const HIDE_CONFIRM_LOGOUT_MODAL = 'HIDE_CONFIRM_LOGOUT_MODAL'
export const SHOW_CONFIRM_DELETE_MEETING_MODAL = 'SHOW_CONFIRM_DELETE_MEETING_MODAL'
export const HIDE_CONFIRM_DELETE_MEETING_MODAL = 'HIDE_CONFIRM_DELETE_MEETING_MODAL'
export const SHOW_CREATE_EDIT_ERROR_MESSAGE = 'SHOW_CREATE_EDIT_ERROR_MESSAGE'
export const HIDE_CREATE_EDIT_ERROR_MESSAGE = 'HIDE_CREATE_EDIT_ERROR_MESSAGE'